---
version: "3.1"
services:
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /opt/v2ray:/etc/v2ray/
      - /lib/modules:/lib/modules
    ports:
      - 9000:9000/udp
      - 9000:9000/tcp
    entrypoint:
      - /usr/bin/v2ray
      - run
      - -config
      - /etc/v2ray/config.json
    restart: always
